In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker as mtick
import seaborn as sns

In [2]:
from data_setup import get_data
data = get_data()
orders_fact = data["orders_fact"]
sessions = data["sessions"]
datetable=data["datetable"]
pageviews=data["pageviews"]

2026-03-06 13:20:51.654 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2026-03-06 13:20:51.671 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2026-03-06 13:20:51.672 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-06 13:20:53.834
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run c:\Users\91853\anaconda3\Lib\site-packages\ipykernel_launcher.py [ARGUMENTS]
2026-03-06 13:20:53.836 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-06 13:20:53.841 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-06 13:20:54.421 Thread 'Thread-3': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-06 13:20:54.433 Thread 'Thread-3': missing ScriptRunContext! This warning can be ignored when running in bare mode.
d:\datascience\Analytix_Internship_data_analyst\digital analytics\streamlit\data_setup.py:18: UserWarning: Parsing dates in %d-%m-%Y %H:%M:%S format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  website_pageviews = pd.read_csv(os.path.join(data_path, "website_pageviews.csv"),usecols=["website_pageview_id","created_at","website_session_id","pageview_url","funnel_step_final"],parse_dates=["created_at"])
d:\datascience\Analytix_Internship_data_analyst\digital analytics\streamlit\data_setup.py:29: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  order_items["order_item_date"] = pd.to_datetime(order_items["order_item_date"], errors="coerce")
d:\datascience\Analytix_Internship_data_analyst\digital analytics\streamlit\data_setup.py:31: UserWarning: Parsing dates in %d-%m-%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  website_sessions["created_at"] = pd.to_datetime(website_sessions["created_at"], errors="coerce")
2026-03-06 13:21:08.580 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-06 13:21:08.595 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [3]:
sessions["created_at"] = pd.to_datetime(sessions["created_at"])

In [4]:
sessions["Year"] = sessions["created_at"].dt.year
sessions["year_q"] = pd.to_datetime(sessions["created_at"]).dt.to_period("Q")

In [5]:
sessions.head()

,website_session_id,created_at,user_id,is_repeat_session,utm_source,utm_campaign,utm_content,device_type,http_referer,session_date,...,MonthName,MonthShort,day_name,DayType,channel_type,session_type,First Session Date,days_since_first_session,days_since_first_session_bin,year_q
0,1,2012-03-19 08:04:00,1,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com,2012-03-19,...,March,Mar,Monday,Weekday,Paid Search,New_Session,2012-03-19 08:04:00,0,0 days,2012Q1
1,2,2012-03-19 08:16:00,2,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com,2012-03-19,...,March,Mar,Monday,Weekday,Paid Search,New_Session,2012-03-19 08:16:00,0,0 days,2012Q1
2,3,2012-03-19 08:26:00,3,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com,2012-03-19,...,March,Mar,Monday,Weekday,Paid Search,New_Session,2012-03-19 08:26:00,0,0 days,2012Q1
3,4,2012-03-19 08:37:00,4,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com,2012-03-19,...,March,Mar,Monday,Weekday,Paid Search,New_Session,2012-03-19 08:37:00,0,0 days,2012Q1
4,5,2012-03-19 09:00:00,5,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com,2012-03-19,...,March,Mar,Monday,Weekday,Paid Search,New_Session,2012-03-19 09:00:00,0,0 days,2012Q1

In [6]:
sessions[["created_at","Year","year_q"]].head()

           created_at  Year  year_q
0 2012-03-19 08:04:00  2012  2012Q1
1 2012-03-19 08:16:00  2012  2012Q1
2 2012-03-19 08:26:00  2012  2012Q1
3 2012-03-19 08:37:00  2012  2012Q1
4 2012-03-19 09:00:00  2012  2012Q1

In [7]:
orders_fact.head()

,order_item_id,created_at_x,order_id,product_id,is_primary_item,price_usd,cogs_usd,order_item_date,order_item_time,Year,...,third_orders,customer_type,customer_lifetime_days,total_items_purchased,cross_sell_orders,cross_sell_order_rate,refund_orders,total_refunded_items,refund_order_rate,refund_prone_customer
0,1,19-03-2012 10:42,1,1,1,49.990002,19.49,2012-03-19,1900-01-01 10:42:46,2012,...,0,One-time Customer,0,1,0,0.0,0,0,0.0,0
1,2,19-03-2012 19:27,2,1,1,49.990002,19.49,2012-03-19,1900-01-01 19:27:37,2012,...,0,One-time Customer,0,1,0,0.0,0,0,0.0,0
2,3,20-03-2012 06:44,3,1,1,49.990002,19.49,2012-03-20,1900-01-01 06:44:45,2012,...,0,One-time Customer,0,1,0,0.0,0,0,0.0,0
3,4,20-03-2012 09:41,4,1,1,49.990002,19.49,2012-03-20,1900-01-01 09:41:45,2012,...,0,One-time Customer,0,1,0,0.0,0,0,0.0,0
4,5,20-03-2012 11:28,5,1,1,49.990002,19.49,2012-03-20,1900-01-01 11:28:15,2012,...,0,One-time Customer,0,1,0,0.0,0,0,0.0,0

In [8]:
pageviews.head()

,website_pageview_id,created_at,website_session_id,pageview_url,funnel_step_final
0,1,2012-03-19 08:04:16,1,/home,Landing Page
1,2,2012-03-19 08:16:49,2,/home,Landing Page
2,3,2012-03-19 08:26:55,3,/home,Landing Page
3,4,2012-03-19 08:37:33,4,/home,Landing Page
4,5,2012-03-19 09:00:55,5,/home,Landing Page

In [9]:
page_session=pageviews.merge(sessions,on="website_session_id",how="left")

In [10]:
page_session.head()

,website_pageview_id,created_at_x,website_session_id,pageview_url,funnel_step_final,created_at_y,user_id,is_repeat_session,utm_source,utm_campaign,...,MonthName,MonthShort,day_name,DayType,channel_type,session_type,First Session Date,days_since_first_session,days_since_first_session_bin,year_q
0,1,2012-03-19 08:04:16,1,/home,Landing Page,2012-03-19 08:04:00,1,0,gsearch,nonbrand,...,March,Mar,Monday,Weekday,Paid Search,New_Session,2012-03-19 08:04:00,0,0 days,2012Q1
1,2,2012-03-19 08:16:49,2,/home,Landing Page,2012-03-19 08:16:00,2,0,gsearch,nonbrand,...,March,Mar,Monday,Weekday,Paid Search,New_Session,2012-03-19 08:16:00,0,0 days,2012Q1
2,3,2012-03-19 08:26:55,3,/home,Landing Page,2012-03-19 08:26:00,3,0,gsearch,nonbrand,...,March,Mar,Monday,Weekday,Paid Search,New_Session,2012-03-19 08:26:00,0,0 days,2012Q1
3,4,2012-03-19 08:37:33,4,/home,Landing Page,2012-03-19 08:37:00,4,0,gsearch,nonbrand,...,March,Mar,Monday,Weekday,Paid Search,New_Session,2012-03-19 08:37:00,0,0 days,2012Q1
4,5,2012-03-19 09:00:55,5,/home,Landing Page,2012-03-19 09:00:00,5,0,gsearch,nonbrand,...,March,Mar,Monday,Weekday,Paid Search,New_Session,2012-03-19 09:00:00,0,0 days,2012Q1

In [11]:
#year_month column
page_session["month_year"] = pd.to_datetime(page_session["Year"].astype(str) + "-" + page_session["MonthNumber"].astype(str))

In [12]:
#group by product page  sessions
product_sessions = (page_session[page_session["funnel_step_final"]=="Product Page"].groupby("month_year")["website_session_id"].nunique().reset_index())

In [13]:
product_sessions = product_sessions.sort_values("month_year")

In [14]:
product_sessions["month_year_str"] = product_sessions["month_year"].dt.strftime("%Y-%m")
product_sessions

   month_year  website_session_id month_year_str
0  2012-03-01                 743        2012-03
1  2012-04-01                1447        2012-04
2  2012-05-01                1585        2012-05
3  2012-06-01                1751        2012-06
4  2012-07-01                2019        2012-07
5  2012-08-01                3011        2012-08
6  2012-09-01                3126        2012-09
7  2012-10-01                4030        2012-10
8  2012-11-01                6744        2012-11
9  2012-12-01                5012        2012-12
10 2013-01-01                3380        2013-01
11 2013-02-01                3685        2013-02
12 2013-03-01                3372        2013-03
13 2013-04-01                4362        2013-04
14 2013-05-01                4683        2013-05
15 2013-06-01                4600        2013-06
16 2013-07-01                5020        2013-07
17 2013-08-01                5226        2013-08
18 2013-09-01                5400        2013-09
19 2013-10-01                6038        2013-10
20 2013-11-01                7885        2013-11
21 2013-12-01                8841        2013-12
22 2014-01-01                7789        2014-01
23 2014-02-01                7961        2014-02
24 2014-03-01                8109        2014-03
25 2014-04-01                9745        2014-04
26 2014-05-01               10260        2014-05
27 2014-06-01               10012        2014-06
28 2014-07-01               10836        2014-07
29 2014-08-01               10769        2014-08
30 2014-09-01               11127        2014-09
31 2014-10-01               12335        2014-10
32 2014-11-01               14476        2014-11
33 2014-12-01               17240        2014-12
34 2015-01-01                7915        2015-01

In [15]:
product_session = (page_session[page_session["funnel_step_final"]=="Product Page"].groupby("year_q")["website_session_id"].nunique().reset_index())

In [16]:
product_session

    year_q  website_session_id
0   2012Q1                 743
1   2012Q2                4783
2   2012Q3                8156
3   2012Q4               15786
4   2013Q1               10437
5   2013Q2               13645
6   2013Q3               15646
7   2013Q4               22764
8   2014Q1               23859
9   2014Q2               30017
10  2014Q3               32732
11  2014Q4               44051
12  2015Q1                7915

In [17]:
page_session[page_session["funnel_step_final"]=="Product Page"]["month_year"].max()

Timestamp('2015-01-01 00:00:00')

In [18]:
#clickthrough rate 
cart_sessions = page_session[page_session["funnel_step_final"] == "Cart"]["website_session_id"].nunique()
prod_sessions=page_session[page_session["funnel_step_final"] == "Product Page"]["website_session_id"].nunique()

In [19]:
cart_sessions

82603

In [20]:
pageviews["pageview_url"].unique()

['/home', '/products', '/the-original-mr-fuzzy', '/cart', '/shipping', ..., '/lander-3', '/the-birthday-sugar-panda', '/lander-4', '/lander-5', '/the-hudson-river-mini-bear']
Length: 16
Categories (16, object): ['/billing', '/billing-2', '/cart', '/home', ..., '/the-birthday-sugar-panda', '/the-forever-love-bear', '/the-hudson-river-mini-bear', '/the-original-mr-fuzzy']

In [21]:
product_ctr = cart_sessions / prod_sessions
print("Product Clickthrough Rate:", round(product_ctr*100,2), "%")

Product Clickthrough Rate: 35.83 %

In [22]:
# clickthorugh rate by month_year
product_month = (page_session[page_session["funnel_step_final"] == "Product Page"].groupby("month_year")["website_session_id"].nunique().reset_index())
cart_month=(page_session[page_session["funnel_step_final"] == "Cart"].groupby("month_year")["website_session_id"].nunique().reset_index())

In [23]:
#merging table for the month_year
ctr_table = product_month.merge(cart_month, on="month_year")
ctr_table.columns = ["month_year", "product_sessions", "cart_sessions"]
ctr_table["clickthrough_rate"] =round( (ctr_table["cart_sessions"] / ctr_table["product_sessions"])*100,2)
ctr_table["month_year_str"] = ctr_table["month_year"].dt.strftime("%Y-%m")

In [24]:
ctr_table

,month_year,product_sessions,cart_sessions,clickthrough_rate,month_year_str
0,2012-03-01,743,229,30.82,2012-03
1,2012-04-01,1447,436,30.13,2012-04
2,2012-05-01,1585,477,30.09,2012-05
3,2012-06-01,1751,559,31.92,2012-06
4,2012-07-01,2019,637,31.55,2012-07
5,2012-08-01,3011,960,31.88,2012-08
6,2012-09-01,3126,985,31.51,2012-09
7,2012-10-01,4030,1258,31.22,2012-10
8,2012-11-01,6744,2090,30.99,2012-11
9,2012-12-01,5012,1604,32.00,2012-12
10,2013-01-01,3380,1148,33.96,2013-01
11,2013-02-01,3685,1350,36.64,2013-02
12,2013-03-01,3372,1117,33.13,2013-03
13,2013-04-01,4362,1528,35.03,2013-04
14,2013-05-01,4683,1608,34.34,2013-05
15,2013-06-01,4600,1616,35.13,2013-06
16,2013-07-01,5020,1764,35.14,2013-07
17,2013-08-01,5226,1779,34.04,2013-08
18,2013-09-01,5400,1786,33.07,2013-09
19,2013-10-01,6038,2046,33.89,2013-10
20,2013-11-01,7885,2643,33.52,2013-11
21,2013-12-01,8841,3136,35.47,2013-12
22,2014-01-01,7789,2889,37.09,2014-01
23,2014-02-01,7961,3004,37.73,2014-02
24,2014-03-01,8109,2993,36.91,2014-03
25,2014-04-01,9745,3655,37.51,2014-04
26,2014-05-01,10260,3888,37.89,2014-05
27,2014-06-01,10012,3653,36.49,2014-06
28,2014-07-01,10836,3902,36.01,2014-07
29,2014-08-01,10769,3985,37.00,2014-08
30,2014-09-01,11127,4059,36.48,2014-09
31,2014-10-01,12335,4587,37.19,2014-10
32,2014-11-01,14476,5449,37.64,2014-11
33,2014-12-01,17240,6730,39.04,2014-12
34,2015-01-01,7915,3053,38.57,2015-01

In [25]:
ctr_table.to_excel(r"D:\datascience\Analytix_Internship_data_analyst\digital analytics\streamlit\output_file\product_sessions_click.xlsx",index=False)

In [26]:
pageviews[pageviews["created_at"].dt.year > 2015]

Empty DataFrame
Columns: [website_pageview_id, created_at, website_session_id, pageview_url, funnel_step_final]
Index: []

In [27]:
pageviews["pageview_url"] = pageviews["pageview_url"].str.strip()

In [28]:
#billing revenue
billing2_launch = pageviews.loc[pageviews["pageview_url"] == "/billing-2", "created_at"].min()
billing_test_window = pageviews[(pageviews["created_at"] >= "2012-07-10") &(pageviews["created_at"] <= "2012-11-10")]
billing_sessions = (billing_test_window[billing_test_window["pageview_url"].isin(["/billing","/billing-2"])][["website_session_id","pageview_url","created_at"]].drop_duplicates("website_session_id"))
order_revenue = (orders_fact.groupby(["order_id","website_session_id"])["total_net_revenue"].sum().reset_index())
billing_orders = billing_sessions.merge(order_revenue,on="website_session_id",how="left")
billing_orders["test_period"] = np.where(billing_orders["created_at"] < billing2_launch,"before_test_revenue","after_test_revenue")
billing_ab_revenue = (billing_orders.pivot_table(index="pageview_url",columns="test_period",values="total_net_revenue",aggfunc="sum").reset_index())
billing_ab_revenue

test_period pageview_url  after_test_revenue  before_test_revenue
0               /billing        13997.200195         19496.101562
1             /billing-2        18546.291016                  NaN

In [29]:
billing_ab_revenue.to_excel(r"D:\datascience\Analytix_Internship_data_analyst\digital analytics\streamlit\output_file\billing.xlsx",index=False)

In [30]:
billing2_launch = pageviews.loc[pageviews["pageview_url"] == "/billing-2", "created_at"].min()
billing2_launch

Timestamp('2012-09-10 00:13:05')

In [31]:
#conversion rate
billing2_launch = pageviews.loc[pageviews["pageview_url"] == "/billing-2", "created_at"].min()
billing_sessions = (pageviews[(pageviews["created_at"] <= "2012-11-10") & (pageviews["pageview_url"].isin(["/billing","/billing-2"]))][["website_session_id","pageview_url","created_at"]].sort_values("created_at").drop_duplicates("website_session_id"))
order_sessions = orders_fact[["website_session_id"]].drop_duplicates()
billing_conv = billing_sessions.merge(order_sessions,on="website_session_id",how="left",indicator=True)
billing_conv["order_flag"] = (billing_conv["_merge"] == "both").astype(int)
billing_conv["test_period"] = np.where(billing_conv["created_at"] <billing2_launch,"before_test","after_test")
billing_conversion = (billing_conv.groupby(["pageview_url","test_period"]).agg(sessions=("website_session_id","count"),orders=("order_flag","sum")).reset_index())
billing_conversion["conversion_rate_%"] = (billing_conversion["orders"] /billing_conversion["sessions"]) * 100
billing_conversion

  pageview_url  test_period  sessions  orders  conversion_rate_%
0     /billing   after_test       657     300          45.662100
1     /billing  before_test      1954     870          44.524053
2   /billing-2   after_test       654     410          62.691131

In [32]:
billing_conversion[["pageview_url","test_period","sessions","orders"]]

  pageview_url  test_period  sessions  orders
0     /billing   after_test       657     300
1     /billing  before_test      1954     870
2   /billing-2   after_test       654     410

In [33]:
#website performance first 8 months
sessions["mon_year"] = pd.to_datetime(sessions["Year"].astype(str) + "-" + sessions["MonthNumber"].astype(str))
start_date=sessions["created_at"].min()
end_date = start_date + pd.DateOffset(months=7)
sessions_first_8 = sessions[(sessions["created_at"] >= start_date) & (sessions["created_at"] <=end_date)]
session_orders = sessions_first_8.merge(orders_fact[["website_session_id","order_id"]],on="website_session_id",how="left")
sessions_count = (session_orders.groupby("mon_year").agg(sessions=("website_session_id","nunique"),orders=("order_id","nunique")).reset_index())
sessions_count["conversion_rate_%"] = round((sessions_count["orders"] /sessions_count["sessions"]) * 100,2)
sessions_count["mon_year"] = sessions_count["mon_year"].dt.strftime("%Y-%m")
sessions_count

  mon_year  sessions  orders  conversion_rate_%
0  2012-03      1879      60               3.19
1  2012-04      3734      99               2.65
2  2012-05      3736     108               2.89
3  2012-06      3963     140               3.53
4  2012-07      4249     169               3.98
5  2012-08      6097     228               3.74
6  2012-09      6546     287               4.38
7  2012-10      4609     206               4.47

In [34]:
sessions_count.to_excel(r"D:\datascience\Analytix_Internship_data_analyst\digital analytics\streamlit\output_file\session_first_8.xlsx",index=False)

In [35]:
#Find first pageview of each session
first_pageviews = (pageviews.sort_values("created_at").groupby("website_session_id").first().reset_index())
# Merge with sessions to get traffic source
first_pageviews = first_pageviews.merge(sessions[["website_session_id","utm_source","utm_campaign"]],on="website_session_id",how="left")
#Filter gsearch nonbrand traffic
first_pageviews = first_pageviews[(first_pageviews["utm_source"] == "gsearch") & (first_pageviews["utm_campaign"] == "nonbrand")]
#Keep only home and lander pages
first_pageviews = first_pageviews[first_pageviews["pageview_url"].isin(["/home","/lander-1"])]
#Test period filter
first_pageviews = first_pageviews[(first_pageviews["created_at"] >= "2012-06-19") &(first_pageviews["created_at"] <= "2012-07-28")]
#Merge orders
orders_flag = orders_fact[["website_session_id"]].drop_duplicates()
test_data = first_pageviews.merge(orders_flag,on="website_session_id",how="left",indicator=True)
test_data["order_flag"] = (test_data["_merge"] == "both").astype(int)
lander_test = (test_data.groupby("pageview_url").agg(sessions=("website_session_id","nunique"),orders=("order_flag","sum")).reset_index())
lander_test["CVR"] = (lander_test["orders"] / lander_test["sessions"]) * 100
lander_test

  pageview_url  sessions  orders       CVR
0        /home      2261      72  3.184432
1    /lander-1      2316      94  4.058722

In [74]:
first_pageviews_after = (pageviews.sort_values("created_at").groupby("website_session_id").first().reset_index())
first_pageviews_after = first_pageviews_after.merge(sessions[["website_session_id","utm_source","utm_campaign"]],on="website_session_id",how="left")
first_pageviews_after = first_pageviews_after[(first_pageviews_after["utm_source"] == "gsearch") & (first_pageviews_after["utm_campaign"] == "nonbrand") & (first_pageviews_after["created_at"] > "2012-07-28")]
sessions_after_test = first_pageviews_after["website_session_id"].nunique()
home_cvr = lander_test.loc[lander_test["pageview_url"]=="/home","CVR"].values[0]
lander_cvr = lander_test.loc[lander_test["pageview_url"]=="/lander-1","CVR"].values[0]
cvr_lift = (lander_cvr - home_cvr) / 100
incremental_orders = sessions_after_test * cvr_lift
avg_order_value = (orders_fact["total_net_revenue"].sum() /orders_fact["order_id"].nunique())


# incremental revenue
incremental_revenue = incremental_orders * avg_order_value
incremental_orders, incremental_revenue

(np.float64(2093.7765600377056), np.float64(120079.40838585018))

In [53]:
#baseline cvr
first_pageviews = (pageviews.sort_values("created_at").groupby("website_session_id").first().reset_index())
first_pageviews = first_pageviews.merge(sessions[["website_session_id","utm_source","utm_campaign"]],on="website_session_id",how="left")
lander_sessions = first_pageviews[(first_pageviews["utm_source"] == "gsearch") & (first_pageviews["utm_campaign"] == "nonbrand") &(first_pageviews["pageview_url"]=="/home")]
baseline = lander_sessions[lander_sessions["created_at"] < "2012-06-19"]
baseline_sessions = baseline["website_session_id"].nunique()
orders_flag = orders_fact[["website_session_id"]].drop_duplicates()
baseline_orders = baseline.merge(orders_flag,on="website_session_id",how="inner")["website_session_id"].nunique()
baseline_cvr = (baseline_orders / baseline_sessions) * 100
baseline_cvr

2.865973588086541

In [54]:
print("Baseline Sessions:", baseline_sessions)
print("Baseline Orders:", baseline_orders)

Baseline Sessions: 10677
Baseline Orders: 306

In [61]:
#test cvr
test_period = first_pageviews[(first_pageviews["utm_source"] == "gsearch") &(first_pageviews["utm_campaign"] == "nonbrand") &(first_pageviews["pageview_url"].isin(["/home","/lander-1"])) &(first_pageviews["created_at"] >= "2012-06-19") &(first_pageviews["created_at"] <= "2012-07-28")]
test_sessions = test_period["website_session_id"].nunique()
test_orders = test_period.merge(orders_flag,on="website_session_id",how="inner")["website_session_id"].nunique()
test_cvr = (test_orders / test_sessions) * 100
test_orders
test_sessions
test_cvr

3.626829801179812

In [68]:
#cvrlift
cvr_diff=(test_cvr-baseline_cvr)/100
cvr_diff

0.00760856213093271

In [70]:
#session_after_test
#incremental_revenue
incre_orders=sessions_after_test*cvr_diff
incre_revenue=incre_orders*avg_order_value
print("incre orders",incre_orders)
print("incre_revenue",incre_revenue)

incre orders 1822.1212848021582
incre_revenue 104499.81